---
abstract: 'Validate Indonesian driving license number (nomor SIM)'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
generated_by: 'Dist::Zilla version 1.100520'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Business-ID-SIM
requires:
  DateTime: 0
  ExtUtils::MakeMaker: 6.11
  Pod::Coverage: 0.18
  Test::More: 0
  Test::Pod::Coverage: 1.08
version: 0.02
